"""
export.py
Geometry file export. Pure standard library -- no Rhino, no numpy.

The engine works in CENTIMETRES throughout. Most downstream tools
(Blender, Rhino set to metres, three.js) expect metres, so every
exporter here takes a `scale` factor defaulting to 0.01 (cm -> m).
Pass scale=1.0 if you genuinely want centimetres out.
"""

from __future__ import annotations

from .growth import FloorPlan
from .massing import MassingBlock, generate_massing, generate_room_massing

CM_TO_M = 0.01

# Face winding for a box built from 4 base corners (1-4) then the same
# 4 at the top (5-8). Quads, counter-clockwise seen from outside.
_BOX_FACES = (
    (4, 3, 2, 1),  # bottom
    (5, 6, 7, 8),  # top
    (1, 2, 6, 5),
    (2, 3, 7, 6),
    (3, 4, 8, 7),
    (4, 1, 5, 8),
)


def _safe_name(s: str) -> str:
    """OBJ group names cannot contain whitespace."""
    return "".join(c if (c.isalnum() or c in "._-") else "_" for c in s)


def blocks_to_obj(blocks: list[MassingBlock], scale: float = CM_TO_M,
                  name: str = "growth_engine") -> str:
    """
    Serialise massing blocks to Wavefront OBJ. Each block becomes one
    box in its own named group, so the result comes into Blender/Rhino
    already separated by element (or by room, if you passed room-level
    massing in).
    """
    lines: list[str] = [
        f"# {name} -- generated by growth_engine.export",
        f"# {len(blocks)} blocks, units: {'metres' if scale == CM_TO_M else f'cm x {scale}'}",
        "",
    ]
    offset = 0
    for i, b in enumerate(blocks):
        lines.append(f"g {i:04d}_{_safe_name(b.label)}")
        for z in (b.z0, b.z1):
            for c in b.base_corners:
                lines.append(f"v {c.x * scale:.4f} {c.y * scale:.4f} {z * scale:.4f}")
        for face in _BOX_FACES:
            idx = " ".join(str(offset + v) for v in face)
            lines.append(f"f {idx}")
        offset += 8
        lines.append("")
    return "\n".join(lines)


def plan_to_obj(plan: FloorPlan, per_room: bool = True,
                scale: float = CM_TO_M) -> str:
    """
    Convenience wrapper: extrude a plan and serialise it in one call.

    per_room=True uses generate_room_massing(), which emits one box per
    REAL room for any unit that has surveyed geometry (and correctly
    stacks a duplex's upper floor via each room's z_min). per_room=False
    gives the coarse one-box-per-element massing instead.
    """
    blocks = generate_room_massing(plan) if per_room else generate_massing(plan)
    return blocks_to_obj(blocks, scale=scale,
                         name="rooms" if per_room else "elements")


def save_obj(plan: FloorPlan, path: str, per_room: bool = True,
             scale: float = CM_TO_M) -> str:
    with open(path, "w", encoding="utf-8") as f:
        f.write(plan_to_obj(plan, per_room=per_room, scale=scale))
    return path
