"""
export.py
Geometry file export. Pure standard library -- no Rhino, no numpy.

The engine works in CENTIMETRES throughout. Most downstream tools
(Blender, Rhino set to metres, three.js) expect metres, so every
exporter here takes a `scale` factor defaulting to 0.01 (cm -> m).
Pass scale=1.0 if you genuinely want centimetres out.
"""

from __future__ import annotations

from .growth import FloorPlan
from .massing import MassingBlock, generate_massing, generate_room_massing

CM_TO_M = 0.01

# Faces are generated per block now rather than read from a fixed table:
# a footprint is no longer always four corners. See blocks_to_obj.


def _safe_name(s: str) -> str:
    """OBJ group names cannot contain whitespace."""
    return "".join(c if (c.isalnum() or c in "._-") else "_" for c in s)


def blocks_to_obj(blocks: list[MassingBlock], scale: float = CM_TO_M,
                  name: str = "growth_engine") -> str:
    """
    Serialise massing blocks to Wavefront OBJ. Each block becomes one
    prism in its own named group, so the result comes into Blender/Rhino
    already separated by element (or by room, if you passed room-level
    massing in).

    A general prism over n corners, not a box. Footprints are no longer
    always four-cornered: green areas are traced region outlines and can
    have any number of sides, and the fixed 8-vertex / 6-quad table this
    used silently wrote the first four corners of a 40-sided garden as a
    box.
    """
    lines: list[str] = [
        f"# {name} -- generated by growth_engine.export",
        f"# {len(blocks)} blocks, units: {'metres' if scale == CM_TO_M else f'cm x {scale}'}",
        "",
    ]
    offset = 0
    for i, b in enumerate(blocks):
        n = len(b.base_corners)
        lines.append(f"g {i:04d}_{_safe_name(b.label)}")
        for z in (b.z0, b.z1):
            for c in b.base_corners:
                lines.append(f"v {c.x * scale:.4f} {c.y * scale:.4f} {z * scale:.4f}")
        base = [offset + k + 1 for k in range(n)]
        top = [offset + n + k + 1 for k in range(n)]
        # Bottom wound backwards so both caps face outward.
        lines.append("f " + " ".join(str(v) for v in reversed(base)))
        lines.append("f " + " ".join(str(v) for v in top))
        for k in range(n):
            k2 = (k + 1) % n
            lines.append(f"f {base[k]} {base[k2]} {top[k2]} {top[k]}")
        offset += 2 * n
        lines.append("")
    return "\n".join(lines)


def plan_to_obj(plan: FloorPlan, per_room: bool = True,
                scale: float = CM_TO_M) -> str:
    """
    Convenience wrapper: extrude a plan and serialise it in one call.

    per_room=True uses generate_room_massing(), which emits one box per
    REAL room for any unit that has surveyed geometry (and correctly
    stacks a duplex's upper floor via each room's z_min). per_room=False
    gives the coarse one-box-per-element massing instead.
    """
    blocks = generate_room_massing(plan) if per_room else generate_massing(plan)
    return blocks_to_obj(blocks, scale=scale,
                         name="rooms" if per_room else "elements")


def save_obj(plan: FloorPlan, path: str, per_room: bool = True,
             scale: float = CM_TO_M) -> str:
    with open(path, "w", encoding="utf-8") as f:
        f.write(plan_to_obj(plan, per_room=per_room, scale=scale))
    return path
